[package]
name = "werewolf-rs-client"
version = "0.1.0"
authors = ["Kai Berszin <mail@kaibersz.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
werewolf-rs = {path = "../werewolf-rs"}
yew = "0.17"