FROM rust:1.51 as base
RUN rustup update nightly; rustup default nightly;
# Build werewolf-rs
FROM base as trunk

RUN user=root cargo install trunk wasm-bindgen-cli
RUN user=root rustup target add wasm32-unknown-unknown

FROM trunk as werewolf_trunk

WORKDIR /werewolf-rs

RUN USER=root cargo new --bin werewolf-rs
RUN user=root cargo new --bin client
RUN user=root cargo new --bin server

COPY ./Cargo.toml .
COPY ./werewolf-rs/Cargo.toml ./werewolf-rs
RUN cargo build --release -p werewolf-rs

COPY ./werewolf-rs/ ./werewolf-rs/
RUN cargo build --release -p werewolf-rs

FROM werewolf_trunk as client
# Build client


COPY ./client/Cargo.toml ./client
RUN cargo build --release -p werewolf-rs-client

COPY ./client/ ./client/
WORKDIR ./client
RUN trunk build --release

CMD ["trunk", "serve", "--release"]