FROM rust:1.51 as base
RUN rustup update nightly; rustup default nightly;
# Build werewolf-rs

RUN USER=root cargo new --bin werewolf-rs
WORKDIR /werewolf-rs
COPY ./werewolf-rs/Cargo.toml .
RUN cargo build --release

COPY ./werewolf-rs .
RUN cargo build --release

FROM base as server
# Build server

WORKDIR /
RUN user=root cargo new --bin server
WORKDIR /server
COPY ./server/Cargo.toml .
RUN cargo build --release

COPY ./server .
RUN cargo build --release


FROM debian:stable as server_executeable

#Copy executable
COPY --from=server /server/target/release/werewolf-rs-server .

#Set the startup command
CMD ["./werewolf-rs-server"]