version: "3.9"
services:
    server:
        build: 
            context: .
            dockerfile: ./Dockerfile_Server
    client:
        build:
            context: .
            dockerfile: ./Dockerfile_Client