FROM werewolfrs/trunk:latest as base

WORKDIR /werewolf-rs

RUN USER=root cargo new --bin werewolf-rs
RUN user=root cargo new --bin client
RUN user=root cargo new --bin server

COPY ./Cargo.toml .
COPY ./werewolf-rs/Cargo.toml ./werewolf-rs
RUN cargo build --release -p werewolf-rs

COPY ./werewolf-rs/ ./werewolf-rs/
RUN cargo build --release -p werewolf-rs

# Build client

COPY ./client/Cargo.toml ./client
RUN cargo build --release -p werewolf-rs-client

COPY ./client/ ./client/
WORKDIR ./client
RUN trunk build --release

FROM nginx
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o /usr/local/bin/envsubst && chmod +x /usr/local/bin/envsubst

COPY --from=base /werewolf-rs/client/dist/ /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf.template
COPY ./nginx/nginx.conf.default /etc/nginx/conf.d/default.conf