FROM rust:1.51 as base
RUN rustup update nightly; rustup default nightly;
# Build werewolf-rs

WORKDIR /werewolf-rs

RUN USER=root cargo new --bin werewolf-rs
RUN user=root cargo new --bin client
RUN user=root cargo new --bin server

COPY ./Cargo.toml .
COPY ./werewolf-rs/Cargo.toml ./werewolf-rs
RUN cargo build --release -p werewolf-rs

COPY ./werewolf-rs ./werewolf-rs
RUN cargo build --release -p werewolf-rs

FROM base as server
# Build server


COPY ./server/Cargo.toml ./server
RUN cargo build --release -p werewolf-rs-server

COPY ./server ./server
RUN cargo build --release -p werewolf-rs-server


FROM debian:stable as server_executeable

#Copy executable
COPY --from=server /werewolf-rs/target/release/werewolf-rs-server .

#Set the startup command
CMD ["./werewolf-rs-client"]