FROM rust:1.51 as base
RUN rustup update nightly; rustup default nightly;
# Build werewolf-rs


WORKDIR /werewolf-rs

RUN USER=root cargo new --bin werewolf-rs
RUN user=root cargo new --bin client
RUN user=root cargo new --bin server

COPY ./Cargo.toml .
COPY ./werewolf-rs/Cargo.toml ./werewolf-rs
RUN cargo build --release -p werewolf-rs

COPY ./werewolf-rs/ ./werewolf-rs/
RUN cargo build --release -p werewolf-rs

FROM base as client
# Build client


COPY ./client/Cargo.toml ./client
RUN cargo build --release -p werewolf-rs-client

COPY ./client/ ./client/
RUN cargo build --release -p werewolf-rs-client
FROM debian:stable

#Copy executable
COPY --from=client /werewolf-rs/target/release/werewolf-rs-client .

#Set the startup command
CMD ["./werewolf-rs-client"]